### ISSUE TITLE
Expansion scenarios for the East North Atlantic (ENA) site

### ISSUE THREAD

**Issue by wgustafson** [ARM-DOE/lasso-public#1]
This thread is for discussing opportunities to expand LASSO to do simulations at ARM's East North Atlantic (ENA) atmospheric observatory. Some background information can be found in the [associated blog entry](https://www.arm.gov/news/blog/post/51594). Additional discussion threads will be created as the [LASSO Expansion blog series](https://www.arm.gov/news-events/search?news-category[0][0]=post&news-category[1][0]=LASSO) focuses on additional sites.

How would you use LASSO simulations for ENA? What types of research would they benefit and how would you apply them? How would you configure a high-resolution model at ENA to complement ARM's observations? Should the model aim to capture mesoscale organization or focus on smaller cloud details? How would you deal with handling island effects on the cloud field?

Note ARM's [Comment Policy](https://github.com/ARM-DOE/lasso-public/wiki/Comment-Policy).

**Comment by eroesler** [comment]
The marine stratocumulus problem in GCMs would be a good issue to tackle using LASSO, seeing if similar problems & bias arise after longer integrations.  WRF has the ability to be run with multiple resolutions and a line-up of parameterization packages to choose from, and hopefully the island effect could be resolved.  Runs from LASSO would be interesting to compare with the RRM-ENA configuration of E3SM, too.   Finally, any sensitivity study of aerosol-cloud interactions would be interesting.

**Comment by wgustafson** [comment]
Closing this issue on GitHub. Folks interested in contributing further thoughts should post a comment in the LASSO category on <https://discourse.arm.gov/c/lasso/lasso-general/11>.
